FROM python:3.10-alpine
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev --no-root
COPY src/broker.py src/config.py src/receiver.py ./
EXPOSE 7000
ENTRYPOINT ["uvicorn", "receiver:app", "--host", "0.0.0.0", "--port", "7000"]